### ISSUE TITLE
[Rss2Email] Вебреквест

### ISSUE THREAD

**Issue by pavel-b-novikov** [saltukkos/nsudotnet#1]
Закрывать кто будет? Пушкин?

**Comment by saltukkos** [comment]
Хотел создать профиль Пушкина и сделать пулл реквест ко мне, но стало лень 1d6f8c7ff14dbcd06a25b50b6fb663e98e5f49c4

**Comment by pavel-b-novikov** [comment]
А был бы скриншот на века
