### ISSUE TITLE
[Enigma] Enigma - графическая часть

### ISSUE THREAD

**Issue by pavel-b-novikov** [saltukkos/nsudotnet#4]
- сертификат пож-та тоже включите в репозиторий. Мне пришлось отключить подписывание, чтобы запустить
- если уж окно не ресайзится - надо отключать кнопочку "развернуть" в настройках бордюра
- я по-моему достаточно времени уделил вопросу неброкирования UI? Так какого хрена во время шифрования визуально окно зависает? (шифровал ISO-образ visual studio aes-ом)
- в пандан к предыдущему: прогрессбар хочу! да, придется перестать использовать няшный CopyTo
- проект инсталлятора у меня не открылся :( по сему - пожалуйста расскажите как планируется добавлять программу в контекстное меню (на словах)

**Comment by saltukkos** [comment]
- А вы уверены, что это нормальная практика, добавлять сертификат в репозиторий? Почему он тогда по умолчанию включён в .gitignore? Может каждый, кто хочет на своём компе собрать сорцы, должен генерировать свой сертификат? (Но ок добавил 4aad52f2c7eb9ce00c06a03c54fa1660f7f84562)
- 565e710c6faaa70ca0d852ce79d737dc8838ea3a
- 677af053970f3f4f52b4c2e3ef790dace570280f
- Чтобы открылся, нужно установить модуль для студии, ну суть такая: делаю работу с параметрами командной строки и в реестр добавляю следующие записи: 
![image](https://cloud.githubusercontent.com/assets/13440397/26284764/db0513be-3e6c-11e7-8ca5-e18d82ccc545.png)
и вот сюда 
![image](https://cloud.githubusercontent.com/assets/13440397/26284761/cdc95cc8-3e6c-11e7-96bf-3108bd1a3396.png) записи: `[INSTALLDIR]Saltuk.Nsudotnet.EnigmaWPFWrapper.exe encrypt %1` и `[INSTALLDIR]Saltuk.Nsudotnet.EnigmaWPFWrapper.exe decrypt %1` соответсвенно

**Comment by saltukkos** [comment]
Вот релиз с .exe-шником https://github.com/saltukkos/nsudotnet/releases/tag/v1.0

**Comment by pavel-b-novikov** [comment]
Про сертификат - все верно, сие есть так, но у меня просто нет свободной минуты перегенерить сертификат
